Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  # Provisionnement avec le script shell exercice1.sh
  config.vm.provision "shell", path: "exercice1.sh"

  # Répertoire partagé entre la machine hôte et la machine virtuelle
  config.vm.synced_folder "html", "/var/www/html"
end